### ISSUE TITLE
bad telemetry

### ISSUE THREAD

**Issue by hedva92** [JiriSvacek/PV_DHW_control#2]
Ahoj, zkoušel jsem nasimulovat svoji telemetrii, ale výsledkem jsou nesmysly. Z jakého protokolu si vycházel? Já mám verzi BMSky 48V 100A a RS485 i pro komunikaci s měničem.. Díky. Michal
![seplos](https://github.com/JiriSvacek/PV_DHW_control_Seplos-BMS/assets/43466773/6ed8a507-502a-4608-919e-4c415c9820ef)

**Comment by JiriSvacek** [comment]
Ahoj,
ještě jsem to dnes znovu zkontroloval a u mně to jede.
![obrazek](https://github.com/JiriSvacek/PV_DHW_control_Seplos-BMS/assets/99678439/49362293-5d48-4d2c-ac7b-838e734a0c3a)
[Tady](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjA2v7to4CEAxVHxQIHHS-OAbAQFnoECBAQAQ&url=https%3A%2F%2Fus.v-cdn.net%2F6034073%2Fuploads%2FOJ8IDWBXR179%2Fseplos-bms-communication-protocol-v2-0.pdf&usg=AOvVaw0sMoDW17CHfBQTg5TIyvF9&opi=89978449) je protocol je to klasicka v2.0, co najdeš na internetu.
Tady co mně to vrací:
```
b'~2000460010960001100CE60CE00CE30CE50CE40CE50CE50CE30CE00CE50CE70CE50CE60CE50CE20CDF060B7D0B7F0B7E0B800BB30B9800A2149F1E970A59D8015459D800F203E814A50000000000000000DC9D\r'
```
Jinak zkontroluj, že máš příkaz pro telemetrii a ne třeba na poslání erroru. Co se tak dívám k tobě tak vypadá podobně, tak bych zkusil "změnit" zarovnání, už nevím proč to 2x ořezávám :-D, ale u mně to funguje a u tebe se dívám, že začátek máš hex podobný, u mně `0001100CE6` u tebe `0002100CED`. `00` DATA FLAG, `01` resp. `02` COMMAND GROUP,`10` je počet packů baterek (16) a za tím už začínají 2 bajty s napětím článku. U mě `3302` (3.302 V), u tebe `0CED` (3.309  V), pak se tyto hodnoty opakuji (zhruba) ještě 15x, pak následuje počet teploměrů `06` 6. a pak se zase opakují teploty po 2 bytech.
Tak by jsi se mněl "dopočítat" k proud atd. Možná to celé smaž a dej tam jen záladní ořez a pak dle pozice co si dopočítáš viz, [models.py](https://github.com/JiriSvacek/PV_DHW_control_Seplos-BMS/blob/3b2af66de1daab63c81b292ce83fb076b2779f09/models.py#L289) pořadí je SOC, proud a napětí.
Snad ti to pomůže.
Jirka

**Comment by hedva92** [comment]
Díky, už to chodí. :)
